### ISSUE TITLE
Add jest snapshot for chapterCard component

### ISSUE THREAD

**Issue by Sboonny** [freeCodeCamp/chapter#1339]
ChapterCard doesn't have snapshot, it would be lovely to add one

- [ ] add jest snapshot for it 

----

<s>
As discussed in #323, the current display of chapter info in the homepage isn't helpful, for that we can do the following

-  add tags to chapter #1344 
- [x] tags should be meaningful #1341
- [x] change how chapter's name is displayed to make it easier to understand #1361 
- [x] display chapter's type #1361 
- [x] display chapter's description #1361 
- [x] remake the presentation #1361 

----

not MVP

- add icons to make them clearer

</s>
