### ISSUE TITLE
Umbrella issue for user feedback

### ISSUE THREAD

**Issue by ojeytonwilliams** [freeCodeCamp/chapter#1839]
Issues uncovered by internal testing

- [ ] Sponsors cannot be seen in the dashboard (the Sponsor tab is missing and Sponsors cannot be added)
- [ ] Unable to unsubscribe from events

These happens because new entries in the initial db (the _instance_permissions_ entry 'sponsors-view' and the chapter permission 'event-subscription-manage' in this case) were not added to the staging db.  The solution is probably to include a script to reset these tables during a deployment.  If/when we allow for custom roles we will need to revisit this.

- [ ] Event updates were not reflected on the home page

Unable to reproduce locally.  Maybe an error was thrown while the event was being updated.

- [ ] Cancelling your RSVP to an event should remove your subscription automatically. 

The 'subscribe' button should stay enabled, but the default assumption is that someone does not want notifications at this point.

- [ ] When you cancel your RSVP you should receive a confirmation email once that has succeeded

- [ ] When your role is changed by someone else you should be notified.

For now I think an email (respecting your notification preferences) will be fine.

- [ ] As a logged out user, you briefly see the 'join this event' modal before being redirected to Auth0

Short term solution: don't show the modal to logged out users.
Long term solution: show it after they complete the login flow.

- [ ] It is not possible to change email address

Possibly not something we can solve before launching the MVP, but it's definitely something we'll need to address

- [ ] Members should be able to see their own email address on their profile

- [ ] Updates to event times should email users

Let's see how annoying this is when everyone is getting emails from both Chapter and Google.

- [ ] The dashboard should be hidden unless you're an owner or admin

Currently the dashboard appears in the menu and you can see http://localhost:3000/dashboard/chapters, http://localhost:3000/dashboard/events and http://localhost:3000/dashboard/venues.  Also, sub dashboards like http://localhost:3000/dashboard/chapters/1/new-venue

This feels like something we should be able to solve with a [dynamic route](https://nextjs.org/docs/routing/dynamic-routes) that rejects anyone without admin or owner permissions.

**Comment by allella** [comment]
This is not adding anything to the list above, but just a reminder of the [Roadmap labeled issues](https://github.com/freeCodeCamp/chapter/issues?q=is%3Aissue+label%3ARoadmap+) for post-MVP in case any of these issues need to be put on ice without being lost.

**Comment by Sboonny** [comment]
Instance owner can't see sponsor page, because the sponsor permission doesn't exist in the database, so its value isn't connected to the instance owner

**Comment by Sboonny** [comment]
> Event updates were not reflected on the home page 

I can't replicate this locally, is it caching latency issue? I.e server lag because of data traveling distance

**Comment by ojeytonwilliams** [comment]
> I can't replicate this locally, is it caching latency issue? I.e server lag because of data traveling distance

Conceivably, if Rafa was clicking very quickly. Let's see if we get any more reports.
