### ISSUE TITLE
Keyboard focus outline issues

### ISSUE THREAD

**Issue by Sboonny** [freeCodeCamp/chapter#1971]
**Describe the bug**
I have navigated the website with Keyboard, and found some issues with focus outline, here are the issue:

- [x] focus over the Logo is cramped, it could use some spacing "adding `offset`", Edit: adding `offset` doesn't work because it's box shadow property. #1972

![image](https://user-images.githubusercontent.com/88248797/204120453-8f9a8dc7-65f9-474b-8573-f85bba6c941b.png)

- [ ] pressing tab while the menu is open doesn't do anything, should we do something about that? If we do something about it, what should we do? Edit: I have checked the docs, and they have it with no effect, maybe it's better this way, we can come back to this when someone asks for it https://chakra-ui.com/docs/components/menu/usage#keyboard-interaction
- [x] the user profile icon next to the menu is focusable, but doesn't have an outline indicating the focus, which may lead to confusion. #1972
- [x] some links have a different outline focus. #1973 

The previous point happens when a link wraps around another element, here is an example

![image](https://user-images.githubusercontent.com/88248797/204120476-dc1a200c-d4cb-4972-a674-9bc76ce92c51.png)
![image](https://user-images.githubusercontent.com/88248797/204120481-665628ba-6601-4765-895f-80c3429fc3fa.png)

The issue
```ts
            <Link data-cy="event-link" href={`/events/${event.id}`}>
              <Heading
                mt={1}
                size="sm"
                as={'h3'}
                fontSize={'xl'}
                fontWeight={700}
              >
                {event.name}
              </Heading>
            </Link>
```

here is how it looks without link having element inside
![image](https://user-images.githubusercontent.com/88248797/204120511-6e1e7ecb-58c6-4b96-b094-d1c2589fd83b.png)

```ts
           <Heading
              mt={1}
              size="sm"
              as={'h3'}
              fontSize={'xl'}
              fontWeight={700}
            >
              <Link data-cy="event-link" href={`/events/${event.id}`} width="100%">
                {event.name}
              </Link>
            </Heading>
```
 
 - [x] in Calander section of the dashboard `/dashboard/calendar`, focusing on auth with google button will show two outlines (it has two focusable elements stacked on top of each others) so it will require tabing an additional time to focus away from it. `linkButton` create a link with a button in it which create this issue, I think we should add simple solution for now, because it's our responsiblity to make it accessible. And try to open issue with it in the `chakra-next-link` for it later. #1974 
 
 the fix is to add `tabIndex={-1}` then change the `_focus` effect to look similar to the other focus outlines.

**Comment by Sboonny** [comment]
The last one is related to a menu, which I don't know better. So I am closing this, until I know more and know what people need more
