### ISSUE TITLE
Documentation for How to Use Chapter as an Organizer or Administrator

### ISSUE THREAD

**Issue by QuincyLarson** [freeCodeCamp/chapter#260]
**Using Chapter as an Administrator**
- [ ] Creating and managing chapter
     - [ ] /dashboard/chapter/new
     - [ ] /dashboard/chapter
     - [ ] /dashboard/chapter/{chapters.id}/edit
- [ ] Creating / Inviting and managing organizers

**Using Chapter as an Organizer (post MVP)**
Note: administrators have all the authorizations of an organizer and will be able to perform these actions as well.

- [ ] Creating and managing events
     - [ ] /dashboard/events/new
     - [ ] /dashboard/events
     - [ ] /dashboard/events/{events.id}/edit
- [ ] Creating and managing venues
     - [ ] /dashboard/venues/new
     - [ ] /dashboard/venues
     - [ ] /dashboard/venues/{venues.id}/edit
- [ ] Creating and managing sponsors
     - [ ] /dashboard/sponsors/new
     - [ ] /dashboard/sponsors
     - [ ] /dashboard/sponsors/{sponsors.id}/edit
- [ ] Chapter and member communications
- [ ] Chapter settings
- [ ] Manage Members and bans
- [ ] Group and event photos
- [ ] Member guide
- [ ] Sharing events

**Comment by allella** [comment]
The checklist here is what has [previously been described as the "organizer" role](https://github.com/freeCodeCamp/chapter/issues/296), so I've changed the title to sync up the terminology.

**Comment by allella** [comment]
@Zeko369 do you have a pending PR to move https://github.com/freeCodeCamp/chapter/tree/master/server/docs to CONTRIBUTING.md?   
@Narutuffy was looking to get involved and I thought it could be an easy first contribution and @Narutuffy has Docker setup and is more familiar with the stack than I am, so he may be able to add other tips or improvements.

**Comment by bappyasif** [comment]
@allella this isn't a 'good first issue' but 'oliver' mentioned it sometimes earlier that chapter might use some immediate help with 'mvp' labels, so yeah im open to get started with this as well, but having no significant knowledge about 'chapter' would it be possible to carry out this task?! thanks

**Comment by allella** [comment]
@bappyasif it's likely still too early to develop a how to guide for the application until we get more user interfaces developed because we'll likely include screenshots and notes about interacting with specific UI elements.

@ojeytonwilliams is there a "routes" file or other list of the routes we've already defined? It seems the how to list above is essentially going to have a 1-to-1 with a specific route in the application.  Perhaps a good task for @bappyasif would be mapping the how-to list to existing and planned routes, so we have a better idea of where to look when it comes time to document these _owner_ interfaces.

**Comment by ojeytonwilliams** [comment]
> is there a "routes" file or other list of the routes we've already defined?

Yeah, we use NextJS for our [routing](https://nextjs.org/docs/routing/introduction), which takes paths inside the `/client/src/pages/` directory and maps them to pages. For example: client/src/pages/dashboard/events/[id]/index.tsx gives you pages like `/dashboard/events/1/`.

We don't do anything more complicated than that. At the moment, all routes can be found in `/client/src/pages/` and they all have that form.

> Perhaps a good task for @bappyasif would be mapping the how-to list to existing and planned routes, so we have a better idea of where to look when it comes time to document these owner interfaces.

That's a great idea. Are you up for that @bappyasif ?

**Comment by bappyasif** [comment]
@ojeytonwilliams yeah, lets do this, maybe you can guide me along with this, so that i can perform this better, thanks :)

**Comment by ojeytonwilliams** [comment]
I don't think you'll run into any issues - the NextJS docs are pretty good and we're doing standard stuff, but, sure, give me a shout if you run into something weird.

Good luck!

**Comment by bappyasif** [comment]
@allella @ojeytonwilliams i'll go through `/client/src/pages/` and try to see if can use "next js - routing" to make it work for custom event indexes for any user

i used react-router before, i hope there will be a lot of similarity between these two, regardless, i see anything confusing, i will reach out to you guys, thanks!!

btw, should i be reaching out for help (regarding implementation) here or 'chapter' channel?!

**Comment by ojeytonwilliams** [comment]
> btw, should i be reaching out for help (regarding implementation) here or 'chapter' channel?!

If you want to know about a specific issue, that's the best place to ask.  If your question is more general, then the chapter channel is a good place for it.

**Comment by allella** [comment]
@bappyasif I've edited the list at the top of this issue to have examples of the routes / paths we'll eventually need to document so it's clear what will need to be covered.  I've also expanded it to include functions of the _administrator_ since they will effectively be a "super-organizers" with additional authorizations, such as creating chapters and inviting _organizers_ to a _chapter_.

![image](https://user-images.githubusercontent.com/1777776/141539614-7d4f0d58-19e3-4ccc-9398-dcc6302b9a74.png)

We don't have all of the MVP routes defined in /client/src/pages/. @ojeytonwilliams is there any benefit to us stubbing out the other paths? Is that what you were suggesting @bappyasif do above?  Or, does it make sense for those to only be defined when they are ready for implementation?

> The client accesses the data via hooks defined in client/src/generated/generated.tsx

Should I update that to _client/src/generated/graphql.tsx_ ?

**Comment by allella** [comment]
I've added a bit more to the _[Owner FAQ](https://github.com/freeCodeCamp/chapter/wiki/Owner-FAQs)_ and [Administrator FAQ](https://github.com/freeCodeCamp/chapter/wiki/Administrator-FAQs) Wiki pages, which are related to this task of documenting these roles.

**Comment by bappyasif** [comment]
@allella thanks a lot for more insight on this, yeah, i agree with your suggestion to documenting what's already have been implemented first,

or we could, go ahead documenting all of them, but only with 'fillers' for those whih are not implemented yet, and write proper documentation when its up and running and ready for it!! how would you concur, im cool with each of those options :)

**Comment by allella** [comment]
Added Sponsors routes / paths to the top of this issue since the are going to be defined via https://github.com/freeCodeCamp/chapter/pull/798

**Comment by bappyasif** [comment]
@allella thanks, noted....

@allella @ojeytonwilliams how do you want me to proceed from here to documenting this or else?! thanks :)

**Comment by allella** [comment]
I'll defer to Oliver on if it's worth stubbing out the undefined MVP routes or if it's best to add them as they are implemented.

**Comment by ojeytonwilliams** [comment]
> I'll defer to Oliver on if it's worth stubbing out the undefined MVP routes or if it's best to add them as they are implemented.

I don't think it it's worth creating an entirely empty page just so we have the route.  It's easier just to note that here and update the note if there's any progress and when it's done.

**Comment by bappyasif** [comment]
okay then, no documentation page for 'routes' as of yet, until all of those are implemented beforehand, is that right?! @ojeytonwilliams

is there anything else that i can do for, here in this issue?! thanks.... @allella  @ojeytonwilliams

**Comment by allella** [comment]
@bappyasif Oliver has added more [good first issues](https://github.com/freeCodeCamp/chapter/issues?q=is%3Aissue+is%3Aopen+label%3A%22Good+First+Issue%22), so it may be best to see if there's a smaller task that doesn't require much upfront knowledge of the application.  For example, #789 might be an easy place to start.

**Comment by techieeliot** [comment]
I could help out with testing this out. I've never seen it, so I would be a good test user.

**Comment by allella** [comment]
@techieeliot I just remembered we have some [FAQ at the bottom of the Vision page](https://github.com/freeCodeCamp/chapter/wiki/Vision#frequently-asked-questions) and those have been there since early on.

I'm thinking we should consolidate these into the other FAQs and then link from the end of the Vision page to these.

[Administrator FAQ](https://github.com/freeCodeCamp/chapter/wiki/Administrator-FAQs
)
[Owner FAQ](https://github.com/freeCodeCamp/chapter/wiki/Owner-FAQs
)

We haven't created an Organizer FAQ page yet, but we can do that too. Though, in chatting with Oliver after [the meeting](https://github.com/freeCodeCamp/chapter/wiki/Meeting-Notes-May-13,-2022) is sounded like the _Organizer_ role may not be implemented right away since it's mostly a subset of what the _Owner_ and _Admins_ are able to do.

Would you want to start out with something like this consolidation task?  Also, I'm not sure if special permissions are needed for the Wiki. I can edit it, but I'm not sure if that's open to anybody, which would sort of defeat the purpose of a Wiki.

**Comment by techieeliot** [comment]
Yes, I’ll consolidate the FAQs.

>

**Comment by allella** [comment]
@techieeliot is this something you'll still have time to work on?

**Comment by techieeliot** [comment]
Yes, I’ll have time.

**Comment by allella** [comment]
The [Vision Statement](https://github.com/freeCodeCamp/chapter/wiki/Vision), [Owner FAQ](https://github.com/freeCodeCamp/chapter/wiki/Owner-FAQs), and [Admistrator FAQ](https://github.com/freeCodeCamp/chapter/wiki/Administrator-FAQs) pages have been update.

If there are suggestions for more FAQs or tweaks, then this issue is still a good place to have those conversations.

**Comment by allella** [comment]
Alright, to summarize the conversation from today related to documentation for accounts:

- We also decided that the initial freeCodeCamp testers don't need as much hand-holding, so we don't need admin docs for the MVP to be officially "ready".
- We may eventually have more "rich" documentation with screenshots, like https://docs.digitalocean.com, but Quincy suggested sticking with text. Also, @Sboonny mentioned that bandwidth can be at a premium in some situations, so we will try to limit having a lot of photos, or else having a mobile view that excludes heavy images in docs.
- There is no organizer role so any initial testers on the fCC _instance_ will get an _admin_ role and will need to trusted not to abuse destructive permissions.

**Comment by allella** [comment]
The MVP label has been removed and we'll close this issue with the existing Roadmap tag, which we'll be using for issues to be addressed post-MVP / post-initial testing.
