### ISSUE TITLE
Documentation for How to Install Chapter as an Owner

### ISSUE THREAD

**Issue by QuincyLarson** [freeCodeCamp/chapter#261]
- [ ] Installing Chapter
- [ ] Create an organizer account
- [ ] How Chapter works
- [ ] How to Setup and Configure 3rd Party Services, such as Google OAuth 2.0 and SMTP

**Comment by allella** [comment]
The checklist here is what has [previously been described as the "administrator" role](https://github.com/freeCodeCamp/chapter/issues/296), so I've changed the title to sync up the terminology.

**Comment by allella** [comment]
It would seem we'll also need to document examples of how to setup and configure any 3rd party dependencies.

So far, it sounds like the administrator will need to establish an account with these 3rd parties and configure Chapter with their specific values.

- Register an application with Google in order to use [OAuth 2.0 for "Sign In with Google" as described in the Passport documentation](https://github.com/jaredhanson/passport-google-oauth2#create-an-application).
- Register with an email service to get SMTP settings to allow for sending emails through a 3rd party, as previously described in #283 and #146.

**Comment by allella** [comment]
@QuincyLarson shared a UI for entering admin 3rd party app keys / credentials on https://github.com/freeCodeCamp/chapter/issues/278#issuecomment-578431386

Re-p
<img width="804" alt="73125755-091cf080-3f70-11ea-8a5f-a92dcc7856f3" src="https://user-images.githubusercontent.com/1777776/73129154-12777e80-3fab-11ea-861d-3eea7ac6aa5a.png">
osting that UI screenshot here as it's most applicable to this issue and #280

**Comment by allella** [comment]
This is not all 100% owner related documentation, but I did want to confirm a few things to [consolidate the technical documentation into CONTRIBUTING.md and the Wiki, per the Jan 25th meeting in the last few bullets.](https://github.com/freeCodeCamp/chapter/wiki/Meeting-Notes-January-25,-2020#re-orientation-and-design-overview)

- @Zeko369 do you have a pending PR to move https://github.com/freeCodeCamp/chapter/tree/master/server/docs to CONTRIBUTING.md?   
- @vkWeb is there anything in https://github.com/freeCodeCamp/chapter/blob/master/docs/how-to-open-a-pull-request.md that we need to move before deleting that file? CONTRIBUTING.md seems to have a more robust PR documentation 
- We can delete /docs as it's only general stubbed out stuff from really early on.
- I've confirmed /docs/images can be deleted.
- @Narutuffy was looking to get involved and I thought it could be an easy first contribution and 
- @Narutuffy has Docker setup and is more familiar with the stack than I am, so he may be able to add other tips or improvements to CONTRIBUTING.md on the technical side.

**Comment by allella** [comment]
@vkWeb  regarding the /docs/images and docs/how-to-open-a-pull-request.md I now see those are used or linked to from within the CONTRIBUTING.md, so we don't want to delete them without consolidating.

Quincy had suggesting making one long technical document and using the Wiki for user docs.

I figure we can use the collapsed sections in CONTRIBUTING.md to make it more usable despite the length.

So, I'm updating the previous bulleted list to indicate those changes.  This conversation is getting out of the realm of "owner" docs, so I'll create a new issue if it gets way off course from #261.

**Comment by allella** [comment]
Related to the owner docs was the desire to [consolidate technical documentation into CONTRIBUTING.md](https://github.com/freeCodeCamp/chapter/issues/360).  Please reply to my earlier technical docs comments / questions on  #360

**Comment by allella** [comment]
Closing since this has been tagged "Roadmap" for post-MVP implementation.
