### ISSUE TITLE
As a user, I can search using the search bar in the navigation (implemented with PostgreSQL queries)

### ISSUE THREAD

**Issue by QuincyLarson** [freeCodeCamp/chapter#349]
As a user I should be able to search through through chapters.

- [ ] Mock-up search bar in Material UI (#414) as seen in [homepage mock-up](https://www.figma.com/proto/q7DikyL3N0c4CUWxHNa97i/Chapter-Prototype?node-id=1%3A2&scaling=scale-down)
- [ ] Implement results query or API call
- [ ] Implement results view with lazy load, or infinity scroll, or pagination

**Comment by allella** [comment]
The backend logic of this has been discussed on #112

**Comment by xarielx** [comment]
@Zeko369 please let me know if you need help setting this up, are you planning to use Axios? We can coordinate at any time after 5 pm eastern time if you need help. Thanks

**Comment by Zeko369** [comment]
We're not using axios, we have our own server/client [implementation](https://github.com/freeCodeCamp/chapter/blob/master/client/services/http-service.ts) with `cross-fetch`.

This should be a part of `eventsQuery` on homepage, so you would actually want to create a redux store for it and everything.
But for simplicity you can just use `cross-fetch` and useState to query some events according to the search param for example `api/v1/events?serach=FooBar`

This is more of a API issue, I'll handle it in a today, but for now you can stub it.

**Comment by xarielx** [comment]
That makes perfect sense. I was including useState into waft I was coding but wasn’t sure if we were tying it to the pre loaded events or all the ones saved on the back end

UF ID: 0903-9139<tel:0903-9139>


On Feb 27, 2020, at 3:55 AM, Fran Zekan <notifications@github.com> wrote:

﻿
[External Email]

We're not using axios, we have our own server/client implementation<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_freeCodeCamp_chapter_blob_master_client_services_http-2Dservice.ts&d=DwMCaQ&c=sJ6xIWYx-zLMB3EPkvcnVg&r=RjXmsQnc1Nqs3ON4MiC_jP_ja-8LDMlGR5rK5BQhg4k&m=XbcwwTc8atwTSlIW4x2GD9v8m-iwkMdkgKPSYMTIfwM&s=XRPAm78ol94L7RYfKOBW6cXx7-XfXqCdGsr8_N0XhRo&e=> with cross-fetch.

This should be a part of eventsQuery on homepage, so you would actually want to create a redux store for it and everything.
But for simplicity you can just use cross-fetch and useState to query some events according to the search param for example api/v1/events?serach=FooBar

This is more of a API issue, I'll handle it in a today, but for now you can stub it.

**Comment by allella** [comment]
Here's a visual of the search bar in the navigation
https://www.figma.com/proto/q7DikyL3N0c4CUWxHNa97i/Chapter-Prototype?node-id=332%3A355&scaling=scale-down

**Comment by allella** [comment]
#414 and the feat/search has much of the search bar mocked up in Material UI

**Comment by Ravichandra-C** [comment]
@Zeko369 Can I work on this issue?

**Comment by Zeko369** [comment]
@Ravichandra-C Hop on it

**Comment by Ravichandra-C** [comment]
@ojeytonwilliams @allella @Zeko369 , Should this be implemented with Full text search of Postgres? Or should this just be a sql query?

**Comment by allella** [comment]
I'll defer to Oliver or the earlier contributors on how to approach this one.

**Comment by Zeko369** [comment]
@Ravichandra-C this project switched to prisma in the meantime, and there is a preview feature in prisma (needs to be enabled but then works) that allows you to do full-text-search from JS without writing any raw SQL.

Take a look [prisma docs for the feature](https://www.prisma.io/docs/concepts/components/prisma-client/full-text-search)

**Comment by ojeytonwilliams** [comment]
That's awesome, thanks for sharing it @Zeko369 

@Ravichandra-C if you want to go ahead with this, go for it.  It's a bit risky to rely on a preview feature, but if there are issues with search it won't render Chapter unusable.

**Comment by ojeytonwilliams** [comment]
In the interests of getting the MVP done, I think this can move to Nice to Have.  It's 100% a feature we want, but we can see how Chapter functions without it first and focus on discovery once we have something to discover. 

@allella do you remember the approach re: Roadmap and so on?  I was wondering if we should have MVP and Roadmap issues both open, but mutually exclusive.  Right now we have some Roadmap issues like https://github.com/freeCodeCamp/chapter/issues/434 which are finished and one https://github.com/freeCodeCamp/chapter/issues/264 that is both MVP and Roadmap.  This is a little counter-intuitive.

**Comment by ojeytonwilliams** [comment]
So: closed Roadmap = nice to have, but for the future, open Roadmap = nice to have, and worth implementing if someone is interested, but low priority

Is that about right?

**Comment by allella** [comment]
We moved the Search feature to the Roadmap since there will initially be about 10 fCC chapters testing the first iteration of the application.

@ojeytonwilliams Roadmap has been used to track issues which we want to at least come back to and not forget. So, there's no rating, but we can remove issues from the Roadmap on a future review.
