### ISSUE TITLE
Road-map to release at freeCodeCamp June Summit

### ISSUE THREAD

**Issue by fletcher-greg** [freeCodeCamp/chapter#376]
# Road Map to June

The plan is to announce Chapter publicly at the freeCodeCamp June Summit. 

In order to release Chapter, the following features will need to be completed.
* [ ] Get Google authentication and calendar API working
* [ ] Make it so people can create groups, and those groups can create events
* [ ] Get search working so people can discover events
* [ ] Make it so people can RSVP for events – which will create an RSVP record in our database and also create a Google calendar event in their personal Google calendar.

# Important Changes
At this time, the Figma **design prototypes** and **UX Flow Chart** do not reflect the current Road-map. This will be addressed shortly. Once updated the links will be added here for ease of access.

**Comment by allella** [comment]
Perhaps this issue can become a GitHub project and issues, instead of a checklist?
https://github.com/freeCodeCamp/chapter/projects/1

There's an existing MVP project which @QuincyLarson setup.  Shall we rename it something else, like "In-Person MVP (Future)" and create a new project called "Online Events MVP".  This would allow the original project scope to remain for future use.

I think all of the issues listed overlap with already exist [MVP issues](https://github.com/freeCodeCamp/chapter/projects/1) and I'd imagine the issues can exist in multiple GitHub projects at the same time.

**Comment by fletcher-greg** [comment]
Agreed. 

I posted it mainly because of a discussion in Discord. People wanting to join the project were asking for a document that outlined a the new roadmap.  So I just quickly collected Quincy's latest roadmap that he posted there.

**Comment by allella** [comment]
Thanks. This was a good reminder, so thanks.  I saw the Discord conversation a couple days ago, but I get all Github notices, so it clued me in on the latest conversation on Discord.

I'll give Quincy a chance to chime in. He may want to create a new Github project that fits his vision and vocabulary. If not, then I'll create one.

**Comment by vkWeb** [comment]
@Zeko369 I think we have now moved on to build what we decided earlier. A self-hosted event management solution. 

So let's close this...?

**Comment by Zeko369** [comment]
Yup, closed it
