### ISSUE TITLE
Improve Node, Docker, Postegres and Other Sections of CONTRIBUTING.md

### ISSUE THREAD

**Issue by allella** [freeCodeCamp/chapter#447]
Jonathan and Tom [pointed out in the meeting that Node 13 is not longer supported](https://github.com/freeCodeCamp/chapter/wiki/Meeting-Notes-March-6,-2021#project-updates).  The [Node release page](https://nodejs.org/en/about/releases/) suggests the same since Node 13 is not an LTS release and was only supported for 6 months.

It seems this Node 13 version was also causing issues with the package.json configuration of npm and node.

In addition, I'm going to work through the CONTRIBUTING.md and get everything running locally with a "fresh set of eyes" since I have yet to actually fire up the server.

A lot of new contributors have been hung up on Docker, so we'll see if any of the recent devs have improvements on the Docker side.
 
There are other consistency and wording changes to be made.

If anybody has suggests on improvements, then feel free to shared and get involved.

List of updates to make

- [x] Make "Chapter" bold and italics - Closed via #448
- [x] Convert explicit links to text links - Closed via #448
- [x] Update Node and npm minimums to Node 14, NPM 6 - Closed via #448
- [x] Add specifics for using Git for Windows / Git Bash / GitHub Desktop - via #466 
- [x] Add section explaining .env and .env.example - via #466
- [x] Fix the typo http//:localhost:3000 under the Viewing the Application section - via #466 
- [x] Update GraphQL link to http://localhost:5000/graphql - Closed via #448
- [x] Connect to Postgres running inside of Docker `psql -h localhost -p 54320 -U postgres` - using the user / password defined in your .env - Closed via #448

**Comment by allella** [comment]
@paizle @dtwilliams10 I could use fresh eyes on this if you have time to review it.

Github won't let me tag reviewers until they are involved in the conversation.

**Comment by paizle** [comment]
I'm using git bash on windows and I think I read something somewhere that yarn has some issues on this platform. When I would run "npm run both" I would a different error message each time relating to typeorm. To get around this, I replaced yarn with npm in package.json:
"both": "concurrently \"yarn dev\" \"yarn --cwd='./client' dev\"",
to
"both": "concurrently \"npm run dev\" \"cd client & npm run dev\"",

Then I was able to get the local (non Docker) setup working with "npm run both"

I'm nowhere near guru level when it comes to node/npm so this was just me following the trail of error messages, research and trying things until it worked.

**Comment by paizle** [comment]
I haven't been able to get the Docker setup working yet. When I try, everything seems to go ok but the browser console shows CORS errors when attempting to connect to the app.

Does anyone else get these CORS errors or is it just me/my platform?

**Comment by allella** [comment]
@paizle what browser is showing the CORS error?  That's a security feature and "localhost" is a unique domain, so it could be a specific browser tweak or that we need to add some CORS headers to the app to bypass the localhost issue.

When you run Docker does it have these success lines as part of the output, as shown in this PR in the Running the App -> Step 2 > Docker Mode section?

**Comment by allella** [comment]
> db_1 | ... LOG: database system is ready to accept connections
> 
> client_1 | ready - started server on http://localhost:3000
> 
> app_1 | Listening on http://localhost:5000/graphql

**Comment by allella** [comment]
Another thought, is the "both" command is using a \ escape character to add a literal double quote to the package.json and that's occasionally a source of edge cases.

Could you try, instead of running "yarn both" to run the individual commands it runs to check the escaping isn't confusing other tools?

```
yarn dev
yarn build:client
```

**Comment by allella** [comment]
@paizle the [ "escape character" not playing nice with git bash and yarn](https://github.com/yarnpkg/yarn/issues/2785#issuecomment-283074263) seems plausible, especially if running the two commands separately fixes your issue.

If that is the issue we may be able to redo the "both" command, but let's see if running the commands separately does the trick.

```
yarn dev
yarn build:client
```

**Comment by paizle** [comment]
> 
> 
> @paizle what browser is showing the CORS error? That's a security feature and "localhost" is a unique domain, so it could be a specific browser tweak or that we need to add some CORS headers to the app to bypass the localhost issue.
> 
> When you run Docker does it have these success lines as part of the output, as shown in this PR in the Running the App -> Step 2 > Docker Mode section?

I do get those success lines. 

With the `yarn db:reset` command I get the following:
C:\Users\Matt\Documents\workspace\chapter\clones\another\Chapter\node_modules\.b
in\typeorm:2
basedir=$(dirname "$(echo "$0" | sed -e 's,\\,/,g')")

...but I can get around this issue by changing package.json:
"typeorm": "ts-node -P tsconfig.server.json ./node_modules/.bin/typeorm",
to:
"typeorm": "ts-node -P tsconfig.server.json ./node_modules/typeorm/cli.js",
(I think this is another issue with git bash on windows)

So, finally, after I run `docker-compose up` it's working this time. (yay! no CORS issues) I think somehow the docker setup was connecting to my local postgres because I explicitly shut down the service this time but I'm not sure if that's true since I don't have a good grasp on how docker works and if that was causing the issue.

**Comment by paizle** [comment]
> 
> 
> Another thought, is the "both" command is using a \ escape character to add a literal double quote to the package.json and that's occasionally a source of edge cases.
> 
> Could you try, instead of running "yarn both" to run the individual commands it runs to check the escaping isn't confusing other tools?
> 
> ```
> yarn dev
> yarn build:client
> ```

Ok I tried both and here are the results (just what seems to be the relevant output):

`$ yarn dev
yarn run v1.22.5
$ ts-node-dev --no-notify -P tsconfig.server.json ./server/app.ts
ts-node-dev ver. 1.0.0-pre.63 (using ts-node ver. 8.10.2, typescript ver. 3.9.7)
(node:4128) UnhandledPromiseRejectionWarning: Error: Entity metadata for Event#s
ponsors was not found. Check if you specified a correct entity object and if it'
s connected in the connection options.
`
`$ yarn build:client
yarn run v1.22.5
$ yarn --cwd='./client' build
error Command "build" not found.
`

**Comment by allella** [comment]
#461 aims to remove yarn, so hopefully that works around the git bash and other yarn issues we talked about trying to document around.

**Comment by allella** [comment]
Closing this as the core items have been improved.

There are a number of troubleshooting errors I've encountered on Windows with Docker and Node, so I'll start a new issue with Troubleshooting topics to cover.
