### ISSUE TITLE
Post-release user stories

### ISSUE THREAD

**Issue by chrismgonzalez** [freeCodeCamp/chapter#84]
Hello team,

Please use this issue to add your ideas for future releases of Chapter.  (e.g. Push notifications)

- [ ] User can add RSVP's to a supported calendar app.  Refer to [this tool](https://github.com/jasonleibowitz/react-add-to-calendar-hoc). See [examples](http://leibowitz.me/react-add-to-calendar-hoc/docs/).
- [ ] I can filter events by date
- [ ] I can filter events by tags (via #117 )
- [ ] As a user, I should be able to indicate "No", that I will not be attending an event (via #125 & #53)
- [ ] The user can save a Chapter's events before joining 
- [ ] The user should also receive the email reminder about their upcoming event. (via #10)
- [ ] The Chapter organizer can reach out to the anonymous user should they choose.
- [ ] As a future participant when I click one of those locations, I can see the "show view" for that event's group, with details about the upcoming event, along with a button to RSVP.
- [ ] Users can log in with other social logins such as Facebook/Github/Twitter/...
- [ ] Add complexity requirements for password.
- [ ] As an organizer I can send private invites to join your Chapter to users or non-users via e-mail.
- [ ] As an organizer I can check-in attendees on the event registration desk with their email_id or chapter_id
- [ ] As an organizer, I can set a sponsor description (via #127)
- [ ] An user can opt to sponsor an event with a "Sponsor Now" or "Be a Sponsor"
- [ ] When electing to sponsor an event, the application will detect if they are a registered user, if not, they will be prompted to (optionally) create an account.
- [ ] As and organizer, I would like search engine optimization to advertise my chapter and events. (via #67)

**Comment by matjack1** [comment]
From https://github.com/freeCodeCamp/chapter/pull/90 

- [ ] Users can log in with other social logins such as Facebook/Github/Twitter/...

**Comment by gideonpraise** [comment]
So I was thinking if there can be room for someone that is not a user to opt-in as a sponsor for an event. Something like a button that says "Sponsor Now" or "Be A Sponsor" (whatever it is) then detects if the user is logged in and if not, he's asked if he wants to sponsor without having to create account...

Some people might like to do things anonymously...

**Comment by bernhard-hofmann** [comment]
"they're asked if they want" makes it gender neutral. Let's avoid bias where we can.

**Comment by gideonpraise** [comment]
@bernhard-hofmann sorry, my bad. You're right. Will update it right away...

**Comment by paschott** [comment]
Allow event details to be entered/displayed.
Allow sponsor details to be entered/displayed.  (for people to know a little more before just seeing a name and clicking a link)

**Comment by allella** [comment]
@chrismgonzalez  I've been encouraging people to create a new issue for a suggested user story. That way we can post comments related to the story and decide if it's a duplicate without having all those comments on this thread.

Then, if the story is unique I've been closing the issue and adding it to the main list with a link so when someone reviews these stories down the road they can easily see all the supporting comments in the specific issue.  #125 and #127 are the most recent examples.

Related-ish, we have a lot of ideas in #1 and I haven't really opened that up for comparison, but there's 77 comments on that issue and it would be a shame if we didn't capture those initial conversations.

I'll try to take a first crack at comparing those #1 comments and seeing how many new user stories are in there.

**Comment by chrismgonzalez** [comment]
@allella Sounds like a good idea to me!  Lots of work to do!

**Comment by QuincyLarson** [comment]
This issue is on the roadmap, which means we will get to it after our MVP. I will close this issue for now so we can focus on resolving our non-roadmap issues first.
